#!/usr/bin/env bash

# Toggles the connection state of a bluetooth device using the devices MAC Address.
# The device MUST already be paired and trusted.
# The device's MAC Address can either be read from an environment variable or put in the function's local variable
# You can find the MAC Address for your desired device by running `bluetoothctl paired-devices` and noting the relevant output.

bt_toggle() {
    # Place the device's MAC Address here if you are using this script as a keyboard shortcut.
    # This is required because the script runs in its own environment when executed as a keyboard shortcut.
    local DEVICE_MAC_ADDR="88:C9:E8:DB:EA:78"

    bluetoothctl info "$DEVICE_MAC_ADDR" | grep --quiet "Connected: no" \
        && bluetoothctl connect "$DEVICE_MAC_ADDR" &> /dev/null \
        || bluetoothctl disconnect "$DEVICE_MAC_ADDR" &> /dev/null
}

bt_toggle

