#!/usr/bin/env bash

i=0
while [ $i -lt 255 ]; do
    j=6
    while [ $j -gt 0 ]; do
        tput setaf "$i"

        esc_code="$(tput setaf "$i" | cat -v)"
        printf " | %12s = %3s" "$esc_code" "$i"

        i=$((i+1))
        j=$((j-1))
    done
    echo
done

