#!/bin/zsh

# Find all git directories under a specified directory or $HOME, by default.
# Uses fd to search for any directory that contains a .git folder.
# Ignores anything under ~/.local/share/ such as
#     ~/.local/share/cargo/*    Contains checkouts for cargo packages
#     ~/.local/share/nvim/*     Contains repos for plugins

lsgit() {
    [[ -f /usr/bin/fd ]] || { echo "fd is required"; return 1 }

    local loc="*.local/share/"
    local dir="${1:-$HOME}"
    [[ -d $dir ]] || { echo "directory $dir not found."; return 1 }

    fd --type directory --exclude $loc --hidden --glob ".git" $dir |\
        rev | cut -d. -f2- | rev    # Cut off ".git/" from fd returned path
}
