#!/usr/bin/env zsh
# vim: set filetype=bash: 

_get_term() {
    local term

    case "$TERM" in
        xterm-ghostty | ghostty | Ghostty ) term="Ghostty"  ;;
        xterm-kitty | kitty | Kitty       ) term="Kitty"    ;;
        * ) term="(?) terminal" ;;
    esac

    echo "$term"
}

set_title() {
    local title="$(_get_term)"
    local cmd="$2"
    cmd=$(builtin echo $cmd | /usr/bin/cut -d' ' -f1)

    [[ -v SCRATCHPAD ]] && title="(scratchpad) $title"
    [[ -n "$cmd" ]] && title+=" - $cmd"

    builtin print -Pn "\033]2;${title}\007"
}
