#!/usr/bin/env bash

PACMAN_UPDATES_FILE="$XDG_CACHE_HOME/pacman.updates"

_check_pacman() {
    date > "$PACMAN_UPDATES_FILE"
    checkupdates > "$PACMAN_UPDATES_FILE"
}

_check_python() {
    :
}

_check_rust() {
    :
}

case "$1" in
    "pacman" ) ;;
    "python" ) ;;
    "rust"   ) ;;
esac
